US04-ForgotPassword
FrFlutter02/Bao_Binh_Quang_Khang_Hoang pull request #12
Opened 2021-07-30 09:19 UTC by TDKBao

2021-07-30 10:41 UTC, thanhphamtrung requested changes
I have a few questions

2021-07-30 10:41 UTC, thanhphamtrung commented on lib/src/screens/forgotpassword_screen.dart
> +class BoxResetPassword extends StatefulWidget {
We should rename this to `ResetPasswordBox`

2021-07-30 10:41 UTC, thanhphamtrung commented on lib/src/screens/forgotpassword_screen.dart
> +    if (widthSizeScreen >= 650) {
What happens when there's a tablet with screen size less than 650?
We should find a way to detect deice type instead of raw screen size.

2021-07-30 10:41 UTC, thanhphamtrung commented on lib/src/screens/forgotpassword_screen.dart
> +  checkForgotPassword(BuildContext context, UserState state) {
I don't think it's necessary to have this logic in a separate function unless there is something I'm missing.

2021-07-30 11:02 UTC, TDKBao commented on lib/src/screens/forgotpassword_screen.dart
> +    if (widthSizeScreen >= 650) {
![image](https://user-images.githubusercontent.com/46661008/127643422-f0bd9abc-9c07-4b02-8687-5d7a241da71f.png)

You can see picture I post, screen < 650 in the world for tablet only 5.46% and if using a tablet for a screen < 650, the user experience will be pretty bad.


I have function to check the length of the screen instead of the raw size.  I will fix it's right now.

2021-07-30 11:03 UTC, TDKBao commented on lib/src/screens/forgotpassword_screen.dart
> +  checkForgotPassword(BuildContext context, UserState state) {
Separated to make it easier to manage logic and there is no need to return any widget, separating will help separate UI code and logic look easier.

2021-07-30 13:35 UTC, TDKBao commented on lib/src/screens/forgotpassword_screen.dart
> +class BoxResetPassword extends StatefulWidget {
![image](https://user-images.githubusercontent.com/46661008/127660743-2e672e63-b615-42a2-872a-b4d9fd5ac7e1.png)

I just rename it. Thank you!

2021-07-30 13:37 UTC, TDKBao commented on lib/src/screens/forgotpassword_screen.dart
> +    if (widthSizeScreen >= 650) {
![image](https://user-images.githubusercontent.com/46661008/127660880-e6305429-2df7-4178-a31e-392b339f1c10.png)
![image](https://user-images.githubusercontent.com/46661008/127660950-0ecaf793-03ce-48e1-9312-8c3526bc02b1.png)

I fixed detect device instead of raw screen size.

2021-08-03 15:47 UTC, thanhphamtrung commented on lib/src/screens/forgotpassword_screen.dart
> +  checkForgotPassword(BuildContext context, UserState state) {
I mean that the state should be handled in bloc so in screen we just need to get what we need in state

2021-08-04 04:18 UTC, TDKBao commented on lib/src/screens/forgotpassword_screen.dart
> +  checkForgotPassword(BuildContext context, UserState state) {
Okay, I just change position state into bloc as you want.

2021-08-10 03:27 UTC, thanhphamtrung approved these changes

2021-08-10 03:27 UTC, merged